apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
  - name: test
    image: hwchiu/test:1.0.0
    args: ["9999"]
  - name: test2
    image: hwchiu/netutils
  imagePullSecrets:
  - name: my-docker-hub
